= aerospace-layout(1)
include::util/man-attributes.adoc[]
:manname: aerospace-layout
// tag::purpose[]
:manpurpose: Change layout of the focused window to the given layout
// end::purpose[]

// =========================================================== Synopsis
== Synopsis
[verse]
// tag::synopsis[]
aerospace layout [-h|--help] [--window-id <window-id>]
                 (h_tiles|v_tiles|h_accordion|v_accordion|h_bsp|v_bsp|tiles|accordion|bsp|horizontal|vertical|tiling|floating)...

// end::synopsis[]

// =========================================================== Description
== Description

// tag::body[]
{manpurpose}

If several arguments are supplied then finds the first argument that doesn't describe the currently active layout, and applies the layout.

*Layout Types:*

* `tiles` - Traditional tiling layout where windows are arranged in a grid
* `accordion` - Layout where windows are stacked and can be expanded/collapsed
* `bsp` - Binary Space Partitioning layout that recursively splits space into binary tree structure, similar to i3wm. New windows intelligently split existing space based on container dimensions
* `floating` - Windows float freely and can be positioned anywhere
* `tiling` - Generic tiling mode (preserves current tiling layout)

*Layout Options:*

* Change both tiling layout and orientation in one go: `h_tiles|v_tiles|h_accordion|v_accordion|h_bsp|v_bsp`
* Change tiling layout but preserve orientation: `tiles|accordion|bsp`
* Change orientation but preserve layout: `horizontal|vertical`
* Toggle floating/tiling mode: `tiling|floating`

// =========================================================== Options
include::./util/conditional-options-header.adoc[]

-h, --help:: Print help

--window-id <window-id>::
include::./util/window-id-flag-desc.adoc[]

// =========================================================== Examples
include::util/conditional-examples-header.adoc[]

* Toggle between `floating` and `tiling` layouts (order of args doesn't matter): +
`aerospace layout floating tiling`

* Toggle orientation (order of args doesn't matter): +
`aerospace layout horizontal vertical`

* Toggle between `tiles` and `accordion` layouts (order of args doesn't matter): +
`aerospace layout tiles accordion`

* Switch to `tiles` layout. Toggle the layout orientation if already in `tiles` layout: +
`aerospace layout tiles horizontal vertical`

* Toggle between `tiles`, `accordion`, and `bsp` layouts (order of args doesn't matter): +
`aerospace layout tiles accordion bsp`

* Switch to horizontal BSP layout: +
`aerospace layout h_bsp`

* Switch to vertical BSP layout: +
`aerospace layout v_bsp`

* Switch to BSP layout and toggle orientation if already in BSP: +
`aerospace layout bsp horizontal vertical`

// end::body[]

// =========================================================== Footer
include::util/man-footer.adoc[]
